# Generated by Django 4.1.4 on 2023-01-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0002_alter_blogcategory_options_alter_blogcomment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
    ]
