# Generated by Django 4.1.4 on 2022-12-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
