# Generated by Django 4.1.5 on 2023-01-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_personnel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
