# Generated by Django 4.1.4 on 2022-12-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0003_alter_student_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateTimeField(default='2022-01-01 00:00:00'),
        ),
    ]
